/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

//import Utilitarios.HintTextFieldUI;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.GhostText;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class TelaCliente extends javax.swing.JFrame 
{

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() 
    {
        initComponents();
        //jButton1.requestFocus();
        //campoPesquisaCliente.setFocusable(true);
        //new HintJTextField(campoPesquisaCliente, "Código ou nome do cliente");
        jPanel1.requestFocusInWindow();
        GhostText gt = new GhostText(campoPesquisaCliente, "Código ou nome do cliente");
        menuBarCliente.add(btnIncluirCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIncluirCliente = new javax.swing.JButton();
        btnPesquisaCliente = new javax.swing.JButton();
        campoPesquisaCliente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        menuBarCliente = new javax.swing.JMenuBar();

        btnIncluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        btnIncluirCliente.setActionCommand("  Incluir");
        btnIncluirCliente.setDisabledIcon(null);
        btnIncluirCliente.setDisabledSelectedIcon(null);
        btnIncluirCliente.setLabel("  Incluir");
        btnIncluirCliente.setMargin(new java.awt.Insets(0, -10, 0, -5));
        btnIncluirCliente.setMaximumSize(new java.awt.Dimension(84, 29));
        btnIncluirCliente.setMinimumSize(new java.awt.Dimension(84, 29));
        btnIncluirCliente.setPreferredSize(new java.awt.Dimension(84, 29));
        btnIncluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirClienteActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Clientes");
        setPreferredSize(new java.awt.Dimension(576, 450));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnPesquisaCliente.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btnPesquisaCliente.setText("Pesquisar");
        btnPesquisaCliente.setMargin(new java.awt.Insets(0, -2, 0, -2));
        btnPesquisaCliente.setMaximumSize(new java.awt.Dimension(104, 29));
        btnPesquisaCliente.setMinimumSize(new java.awt.Dimension(104, 29));
        btnPesquisaCliente.setPreferredSize(new java.awt.Dimension(104, 29));
        btnPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        setJMenuBar(menuBarCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(campoPesquisaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                        .addGap(7, 7, 7)
                        .addComponent(btnPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(414, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaClienteActionPerformed
        
        //if(campoPesquisaCliente.
    }//GEN-LAST:event_btnPesquisaClienteActionPerformed

    private void btnIncluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirClienteActionPerformed
        if (!mostrandoTelaIncluirCliente) 
        {
            try {
                new TelaClienteIncluir().setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(TelaCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            mostrandoTelaIncluirCliente = true;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Uma tela de cadastro já está aberta. \nFeche-a para abrir outra!");
        }
    }//GEN-LAST:event_btnIncluirClienteActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //Quando a tela de Clientes for fechada, mudar a flag que evita a abertura de várias para falso.
        TelaPrincipal.mostrandoTelaClientes = false;
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new TelaCliente().setVisible(true);
            }
        });
    }

    //Flags
    public static boolean mostrandoTelaIncluirCliente = false;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncluirCliente;
    private javax.swing.JButton btnPesquisaCliente;
    private javax.swing.JTextField campoPesquisaCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBarCliente;
    // End of variables declaration//GEN-END:variables
}
