/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import banco.Banco;
import dados.Cliente;
import java.sql.Date;
import java.util.Calendar;
import utilitarios.LtpUtil;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import util.GhostText;

/**
 *
 * @author usuario
 */
public class TelaClienteIncluir extends javax.swing.JFrame 
{

    /**
     * Creates new form TelaClienteIncluir
     */
    public TelaClienteIncluir() throws ParseException 
    {
        initComponents();
        jPanel1.requestFocus();
        //int cod = pesqUltimoCodCliente();
        //if (cod != 0)
        //{
          //  campoCodIC.setText(cod + "");
        //}
        ArrayList<String> uf = inicializarComboBox();
        campoUfIC.setModel(new DefaultComboBoxModel(new Vector(uf)));
        campoDataIC.setText(descobrirDataString());
        setarMascaras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoDataIC = new javax.swing.JTextField();
        campoEmailIC = new javax.swing.JTextField();
        campoCidadeIC = new javax.swing.JTextField();
        campoBairroIC = new javax.swing.JTextField();
        campoEnderecoIC = new javax.swing.JTextField();
        campoNomeIC = new javax.swing.JTextField();
        btnCadastrarCliente = new javax.swing.JButton();
        campoUfIC = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        campoCepIC = new javax.swing.JFormattedTextField();
        campoTelefoneIC = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Incluir Cliente");
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(576, 430));
        setMinimumSize(new java.awt.Dimension(576, 426));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Endereço:");

        jLabel4.setText("Bairro:");

        jLabel5.setText("Cidade:");

        jLabel6.setText("UF:");

        jLabel7.setText("CEP:");

        jLabel8.setText("Telefone fixo:");

        jLabel9.setText("Email:");

        jLabel10.setText("Data inclusão:");

        campoDataIC.setForeground(new java.awt.Color(51, 51, 51));
        campoDataIC.setFocusable(false);
        campoDataIC.setRequestFocusEnabled(false);

        campoEnderecoIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEnderecoICActionPerformed(evt);
            }
        });

        btnCadastrarCliente.setText("Incluir");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        try {
            campoCepIC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCepIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCepICActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCidadeIC, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoTelefoneIC))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoNomeIC, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoEnderecoIC, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoBairroIC, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCepIC, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoUfIC, 0, 454, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoDataIC)
                                    .addComponent(campoEmailIC, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnCadastrarCliente)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNomeIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoEnderecoIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoBairroIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoCidadeIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoUfIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoCepIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefoneIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoEmailIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoDataIC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarCliente))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //Quando a tela de inclusão de clientes for fechada, mudar a flag que evita a abertura de várias para falso.
        TelaCliente.mostrandoTelaIncluirCliente = false;
    }//GEN-LAST:event_formWindowClosed

    private void campoEnderecoICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEnderecoICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEnderecoICActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        
        String camposInvalidos = validarEntradas();
        if(camposInvalidos.equals(""))
        {
            int opcao = JOptionPane.showConfirmDialog(this, "Deseja realmente cadastrar esse cliente?", "Confirmar cadastro", JOptionPane.INFORMATION_MESSAGE);
            
            if (opcao == JOptionPane.YES_OPTION)
            {
                String telefone;
                if (campoTelefoneIC.getText().equalsIgnoreCase("Apenas números (DDD + 8 dígitos) - Opcional"))
                {
                    telefone = "";
                }
                else
                {
                    telefone = campoTelefoneIC.getText();
                    telefone = telefone.replace("(", "");
                    telefone = telefone.replace(")", "");
                    telefone = telefone.replace("-", "");
                    telefone = telefone.replace(" ", "");
                }
                
                String email = "";
                if (!campoEmailIC.getText().equalsIgnoreCase("Opcional"))
                {
                    email = campoEmailIC.getText().toUpperCase();
                }
                else
                {
                    email = "";
                }
                
                String cep;
                cep = campoCepIC.getText();
                cep = cep.replace(".", "");
                cep = cep.replace("-", "");
                
                System.err.println(telefone);
                System.err.println(campoCepIC.getText());
                
                Cliente cliente = new Cliente(
                        campoNomeIC.getText().toUpperCase(),
                        campoEnderecoIC.getText().toUpperCase(),
                        campoBairroIC.getText().toUpperCase(), 
                        campoCidadeIC.getText().toUpperCase(), 
                        campoUfIC.getSelectedItem().toString().toUpperCase(),
                        cep, 
                        telefone, 
                        email, 
                        descobrirDataDate());
                
                try
                {
                    Banco.abrirConexao();
                    Banco.adicionarCliente(cliente);
                    JOptionPane.showMessageDialog(this, "Cliente '" + cliente.getNome() + "' cadastrado!\nSeu código será: " + Banco.pesqCodUltimoCliente(), "Operação realizada com sucesso", JOptionPane.INFORMATION_MESSAGE);
                    Banco.fecharConexao();
                    dispose();
                    
                } 
                catch (SQLException ex)
                {
                    Logger.getLogger(TelaClienteIncluir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Verifique o(s) campo(s):\n" + camposInvalidos, "Entrada(s) inválida(s)!", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void campoCepICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCepICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCepICActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClienteIncluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClienteIncluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClienteIncluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClienteIncluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                try 
                {
                    new TelaClienteIncluir().setVisible(true);
                } 
                catch (ParseException ex) 
                {
                    Logger.getLogger(TelaClienteIncluir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JTextField campoBairroIC;
    public static javax.swing.JFormattedTextField campoCepIC;
    private javax.swing.JTextField campoCidadeIC;
    private javax.swing.JTextField campoDataIC;
    private javax.swing.JTextField campoEmailIC;
    private javax.swing.JTextField campoEnderecoIC;
    private javax.swing.JTextField campoNomeIC;
    public static javax.swing.JFormattedTextField campoTelefoneIC;
    private javax.swing.JComboBox<String> campoUfIC;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private Date descobrirDataDate()
    {
        return (new Date(Calendar.getInstance().getTimeInMillis()));
    }
    
    private String descobrirDataString() 
    {
        Date data = descobrirDataDate();
        return LtpUtil.formatarData(data, "dd/MM/yyyy");
    }

//    private int pesqUltimoCodCliente() 
//    {
//        int cod = 0;
//        try 
//        {
//            Banco.abrirConexao();
//            cod = Banco.pesqCodUltimoCliente() + 1;
//            
//        } 
//        catch (SQLException e) 
//        {
//            System.out.println(e.getMessage());
//        }
//        return cod;
//    }

    private ArrayList<String> inicializarComboBox() 
    {
        ArrayList<String> uf = new ArrayList<>();
        
        try 
        {
            Banco.abrirConexao();
            uf = Banco.recuperarEstados();
            Banco.fecharConexao();
        } 
        catch (SQLException e) 
        {
            System.out.println(e.getMessage());
        }
        return uf;
    }

    private String validarEntradas()
    {
        String resp = "";
        
        new GhostText(campoEnderecoIC, "Campo obrigatório");
        new GhostText(campoBairroIC, "Campo obrigatório");
        new GhostText(campoEmailIC, "Opcional");
        new GhostText(campoTelefoneIC, "Apenas números (DDD + 8 dígitos) - Opcional");
        new GhostText(campoCepIC, "Apenas números");
        new GhostText(campoCidadeIC, "Campo obrigatório");
        //Valida Nome
        if(campoNomeIC.getText().equals("Mínimo de 2 nomes"))
        {            
            resp += "Nome\n";
        }
        else if (campoNomeIC.getText().trim().equals(""))
        {
            resp += "Nome\n";
        }
        
        //Valida endereço
        if (campoEnderecoIC.getText().equalsIgnoreCase("Campo obrigatório"))
        {
            resp += "Endereço\n";
        }
        else if (campoEnderecoIC.getText().trim().equals(""))
        {
            resp += "Endereço\n";
        }
        
        //Valida bairro
        if (campoBairroIC.getText().equalsIgnoreCase("Campo obrigatório"))
        {
            resp += "Bairro\n";
        }
        else if (campoBairroIC.getText().trim().equals(""))
        {
            resp += "Bairro\n";
        }
        
        //Valida cidade
        if (campoCidadeIC.getText().equalsIgnoreCase("Campo obrigatório"))
        {
            resp += "Cidade\n";
        }
        else if (campoCidadeIC.getText().trim().equals(""))
        {
            resp += "Cidade\n";
        }
        
        //Valida UF
        if(campoUfIC.getSelectedItem().equals("Selecione"))
        {
            resp += "UF\n";
        }
        
        
        //Valida CEP
        if (!campoCepIC.getText().equalsIgnoreCase("Apenas números")) 
        {
            if (!campoCepIC.getText().trim().matches("[0-9]{2}[.][0-9]{3}[-][0-9]{3}")) 
            {
                resp += "CEP\n";
            }
        }
        else
        {
            resp += "CEP\n";
        }
        
        //Valida telefone
        if (!campoTelefoneIC.getText().equalsIgnoreCase("Apenas números (DDD + 8 dígitos) - Opcional"))
        {
            if (campoTelefoneIC.getText().length() != 14) 
            {
                resp += "Telefone\n";
            }
            else
            {
                for (int i = 0; i < campoTelefoneIC.getText().length(); i++)
                {
                    if ((campoTelefoneIC.getText().charAt(i) < 48 || campoTelefoneIC.getText().charAt(i) > 57) &&
                       campoTelefoneIC.getText().charAt(i) != '(' && campoTelefoneIC.getText().charAt(i) != ')' && 
                       campoTelefoneIC.getText().charAt(i) != ' ' && campoTelefoneIC.getText().charAt(i) != '-')
                    {
                        
                        System.err.println(campoTelefoneIC.getText().charAt(i));
                        resp += "Telefone\n";
                        break;
                    }
                }
            }
        }
        
        //Validar email
        if (!campoEmailIC.getText().equalsIgnoreCase("Opcional")) 
        {
            if (!LtpUtil.validarEmail(campoEmailIC.getText().trim())) 
            {
                resp += "E-mail";
            }
        }
        return resp;
    }

    private void setarMascaras() 
    {
        GhostText ghostText = new GhostText(campoNomeIC, "Campo obrigatório");
        GhostText ghostText1 = new GhostText(campoEnderecoIC, "Campo obrigatório");
        GhostText ghostText2 = new GhostText(campoBairroIC, "Campo obrigatório");
        GhostText ghostText6 = new GhostText(campoEmailIC, "Opcional");
        GhostText ghostText3 = new GhostText(campoTelefoneIC, "Apenas números (DDD + 8 dígitos) - Opcional");
        GhostText ghostText4 = new GhostText(campoCepIC, "Apenas números");
        GhostText ghostText5 = new GhostText(campoCidadeIC, "Campo obrigatório");
    }
}
